[project]
name = "filexa"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.4",
    "pypdf>=6.6.2",
    "pypdf2>=3.0.1",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]
